export const basicWords = [
  {
    title: "Hello",
    word_origin: "Saludo común",
    word_target: "Hello, how are you?",
    examples: ["Hello, my name is Jorge", "Hello everyone!"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Goodbye",
    word_origin: "Despedida",
    word_target: "Goodbye, see you soon",
    examples: ["Goodbye my friend", "Goodbye for now"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Thank you",
    word_origin: "Expresión de gratitud",
    word_target: "Thank you for your help",
    examples: ["Thank you very much", "Thank you so much"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Please",
    word_origin: "Palabra de cortesía",
    word_target: "Please pass the salt",
    examples: ["Please help me", "Please come here"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Yes",
    word_origin: "Afirmación",
    word_target: "Yes, I agree",
    examples: ["Yes, that's correct", "Yes, I understand"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "No",
    word_origin: "Negación",
    word_target: "No, I don't think so",
    examples: ["No, thank you", "No, I can't"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Sorry",
    word_origin: "Disculpa",
    word_target: "Sorry, I made a mistake",
    examples: ["Sorry about that", "I'm sorry for being late"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Excuse me",
    word_origin: "Llamar la atención",
    word_target: "Excuse me, where is the bathroom?",
    examples: ["Excuse me, can you help me?", "Excuse me, sir"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "What",
    word_origin: "Pregunta sobre cosa",
    word_target: "What is your name?",
    examples: ["What time is it?", "What do you want?"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "When",
    word_origin: "Pregunta sobre tiempo",
    word_target: "When are you coming?",
    examples: ["When is the meeting?", "When did you arrive?"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Where",
    word_origin: "Pregunta sobre lugar",
    word_target: "Where is the station?",
    examples: ["Where do you live?", "Where are you going?"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Who",
    word_origin: "Pregunta sobre persona",
    word_target: "Who is your friend?",
    examples: ["Who called you?", "Who are they?"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Why",
    word_origin: "Pregunta sobre razón",
    word_target: "Why are you here?",
    examples: ["Why did you leave?", "Why is it important?"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "How",
    word_origin: "Pregunta sobre manera",
    word_target: "How are you today?",
    examples: ["How do you do it?", "How much is it?"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "I",
    word_origin: "Pronombre personal",
    word_target: "I am a developer",
    examples: ["I like programming", "I am from Mexico"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "You",
    word_origin: "Pronombre personal",
    word_target: "You are welcome",
    examples: ["You are smart", "You can do it"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "He",
    word_origin: "Pronombre personal masculino",
    word_target: "He is a mechanic",
    examples: ["He works hard", "He is from Torreón"],
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    progress: 0,
  },
  {
    title: "She",
    word_origin: "Pronombre personal femenino",
    word_target: "She is a teacher",
    examples: ["She likes reading", "She is very kind"],
    image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    progress: 0,
  },
  {
    title: "It",
    word_origin: "Pronombre para cosas",
    word_target: "It is a car",
    examples: ["It's beautiful", "It works well"],
    image_url: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400",
    progress: 0,
  },
  {
    title: "We",
    word_origin: "Pronombre plural inclusivo",
    word_target: "We are developers",
    examples: ["We work together", "We are friends"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "They",
    word_origin: "Pronombre plural",
    word_target: "They are students",
    examples: ["They are happy", "They live here"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "My",
    word_origin: "Pronombre posesivo",
    word_target: "This is my house",
    examples: ["My name is Jorge", "My car is red"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    title: "Your",
    word_origin: "Pronombre posesivo",
    word_target: "What is your name?",
    examples: ["Your book is here", "Your phone is ringing"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "His",
    word_origin: "Pronombre posesivo masculino",
    word_target: "This is his bicycle",
    examples: ["His house is big", "His job is interesting"],
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    progress: 0,
  },
  {
    title: "Her",
    word_origin: "Pronombre posesivo femenino",
    word_target: "This is her desk",
    examples: ["Her dress is beautiful", "Her name is Maria"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Is",
    word_origin: "Verbo ser/estar",
    word_target: "This is important",
    examples: ["She is a doctor", "It is sunny today"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Are",
    word_origin: "Verbo ser/estar",
    word_target: "You are amazing",
    examples: ["We are friends", "They are here"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Am",
    word_origin: "Verbo ser/estar",
    word_target: "I am happy",
    examples: ["I am a developer", "I am learning English"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Have",
    word_origin: "Verbo tener",
    word_target: "I have a car",
    examples: ["You have time", "They have books"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Has",
    word_origin: "Verbo tener (tercera persona)",
    word_target: "He has a laptop",
    examples: ["She has money", "It has wheels"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Do",
    word_origin: "Verbo hacer",
    word_target: "What do you do?",
    examples: ["I do my homework", "You do great work"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Does",
    word_origin: "Verbo hacer (tercera persona)",
    word_target: "Does he like it?",
    examples: ["She does her best", "It does work"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Go",
    word_origin: "Verbo ir",
    word_target: "Let's go to the beach",
    examples: ["I go to work", "We go together"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "Come",
    word_origin: "Verbo venir",
    word_target: "Come here, please",
    examples: ["She comes tomorrow", "They come early"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Like",
    word_origin: "Verbo gustar",
    word_target: "I like programming",
    examples: ["You like coffee", "They like sports"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Love",
    word_origin: "Verbo amar",
    word_target: "I love my family",
    examples: ["She loves her job", "We love this place"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    title: "Want",
    word_origin: "Verbo querer",
    word_target: "I want to learn English",
    examples: ["Do you want coffee?", "They want to help"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Need",
    word_origin: "Verbo necesitar",
    word_target: "I need your help",
    examples: ["She needs a break", "We need time"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Can",
    word_origin: "Verbo modal (poder)",
    word_target: "I can help you",
    examples: ["You can do it", "He can speak Spanish"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Make",
    word_origin: "Verbo hacer/crear",
    word_target: "Let's make a plan",
    examples: ["I make websites", "She makes coffee"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Take",
    word_origin: "Verbo tomar",
    word_target: "Take this book",
    examples: ["I take a break", "You take the first turn"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Give",
    word_origin: "Verbo dar",
    word_target: "Give me the keys",
    examples: ["I give you my word", "She gives advice"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Work",
    word_origin: "Verbo trabajar",
    word_target: "I work as a mechanic",
    examples: ["You work hard", "We work together"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Learn",
    word_origin: "Verbo aprender",
    word_target: "I learn every day",
    examples: ["You learn fast", "They learn English"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Think",
    word_origin: "Verbo pensar",
    word_target: "I think it's good",
    examples: ["You think too much", "She thinks it's funny"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Know",
    word_origin: "Verbo saber/conocer",
    word_target: "I know the answer",
    examples: ["You know me well", "Do they know about it?"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Say",
    word_origin: "Verbo decir",
    word_target: "What do you say?",
    examples: ["I say it's time", "She says hello"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "See",
    word_origin: "Verbo ver",
    word_target: "I see the problem",
    examples: ["You see it too", "They see the light"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Get",
    word_origin: "Verbo obtener",
    word_target: "I get it now",
    examples: ["You get the idea", "She gets tired easily"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Man",
    word_origin: "Sustantivo hombre",
    word_target: "That man is tall",
    examples: ["A man walked in", "The man works here"],
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    progress: 0,
  },
  {
    title: "Woman",
    word_origin: "Sustantivo mujer",
    word_target: "The woman is smart",
    examples: ["A woman called you", "The woman teaches well"],
    image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    progress: 0,
  },
  {
    title: "Child",
    word_origin: "Sustantivo niño",
    word_target: "The child is happy",
    examples: ["A child is playing", "The children laugh"],
    image_url: "https://images.unsplash.com/photo-1503454537688-e47a5cb0adf0?w=400",
    progress: 0,
  },
  {
    title: "Day",
    word_origin: "Sustantivo día",
    word_target: "Today is a good day",
    examples: ["Every day is new", "The day is sunny"],
    image_url: "https://images.unsplash.com/photo-1495567720989-cebfdc6d5fb3?w=400",
    progress: 0,
  },
  {
    title: "Night",
    word_origin: "Sustantivo noche",
    word_target: "Good night, friend",
    examples: ["The night is quiet", "All night long"],
    image_url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=400",
    progress: 0,
  },
  {
    title: "Time",
    word_origin: "Sustantivo tiempo",
    word_target: "What time is it?",
    examples: ["It's time to go", "We have time"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    title: "House",
    word_origin: "Sustantivo casa",
    word_target: "This is my house",
    examples: ["A big house", "Go to the house"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    title: "Car",
    word_origin: "Sustantivo coche",
    word_target: "I have a car",
    examples: ["A red car", "The car is fast"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Book",
    word_origin: "Sustantivo libro",
    word_target: "I like this book",
    examples: ["A good book", "Read the book"],
    image_url: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400",
    progress: 0,
  },
  {
    title: "Water",
    word_origin: "Sustantivo agua",
    word_target: "Drink some water",
    examples: ["Clear water", "The water is cold"],
    image_url: "https://images.unsplash.com/photo-1509803874385-db7c23645e71?w=400",
    progress: 0,
  },
  {
    title: "Food",
    word_origin: "Sustantivo comida",
    word_target: "The food is delicious",
    examples: ["Good food", "Eat your food"],
    image_url: "https://images.unsplash.com/photo-1495577913117-a0241e4ec97d?w=400",
    progress: 0,
  },
  {
    title: "Money",
    word_origin: "Sustantivo dinero",
    word_target: "I need money",
    examples: ["Save money", "Spend money wisely"],
    image_url: "https://images.unsplash.com/photo-1553729754-5f935e49c61a?w=400",
    progress: 0,
  },
  {
    title: "Computer",
    word_origin: "Sustantivo computadora",
    word_target: "I use a computer",
    examples: ["A fast computer", "The computer works"],
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    progress: 0,
  },
  {
    title: "Phone",
    word_origin: "Sustantivo teléfono",
    word_target: "My phone is ringing",
    examples: ["A new phone", "Check your phone"],
    image_url: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400",
    progress: 0,
  },
  {
    title: "Friend",
    word_origin: "Sustantivo amigo",
    word_target: "You are my friend",
    examples: ["A good friend", "Make new friends"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Family",
    word_origin: "Sustantivo familia",
    word_target: "My family is happy",
    examples: ["A big family", "Family is important"],
    image_url: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400",
    progress: 0,
  },
  {
    title: "Work",
    word_origin: "Sustantivo trabajo",
    word_target: "I love my work",
    examples: ["Hard work", "Go to work"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "School",
    word_origin: "Sustantivo escuela",
    word_target: "Go to school",
    examples: ["A good school", "The school is big"],
    image_url: "https://images.unsplash.com/photo-1427504494785-cdfe4e2e4e28?w=400",
    progress: 0,
  },
  {
    title: "City",
    word_origin: "Sustantivo ciudad",
    word_target: "I live in a city",
    examples: ["A big city", "The city is busy"],
    image_url: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400",
    progress: 0,
  },
  {
    title: "Country",
    word_origin: "Sustantivo país",
    word_target: "Mexico is my country",
    examples: ["A beautiful country", "Visit the country"],
    image_url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    progress: 0,
  },
  {
    title: "Hand",
    word_origin: "Sustantivo mano",
    word_target: "Raise your hand",
    examples: ["Right hand", "Hold my hand"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    title: "Head",
    word_origin: "Sustantivo cabeza",
    word_target: "My head hurts",
    examples: ["Shake your head", "The head office"],
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    progress: 0,
  },
  {
    title: "Eye",
    word_origin: "Sustantivo ojo",
    word_target: "Look in my eye",
    examples: ["Blue eyes", "Close your eyes"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    title: "Heart",
    word_origin: "Sustantivo corazón",
    word_target: "Follow your heart",
    examples: ["A kind heart", "From the heart"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    title: "Color",
    word_origin: "Sustantivo color",
    word_target: "What's your favorite color?",
    examples: ["A bright color", "Choose a color"],
    image_url: "https://images.unsplash.com/photo-1551888016-10a93f3a77b0?w=400",
    progress: 0,
  },
  {
    title: "Number",
    word_origin: "Sustantivo número",
    word_target: "Call this number",
    examples: ["A big number", "What number is it?"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    title: "Good",
    word_origin: "Adjetivo bueno",
    word_target: "That's a good idea",
    examples: ["Good morning", "Good job"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Bad",
    word_origin: "Adjetivo malo",
    word_target: "This is bad weather",
    examples: ["A bad day", "Bad luck"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Big",
    word_origin: "Adjetivo grande",
    word_target: "A big house",
    examples: ["A big tree", "Too big"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "Small",
    word_origin: "Adjetivo pequeño",
    word_target: "A small dog",
    examples: ["Small size", "Very small"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Hot",
    word_origin: "Adjetivo caliente",
    word_target: "The coffee is hot",
    examples: ["A hot day", "Hot water"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "Cold",
    word_origin: "Adjetivo frío",
    word_target: "It's very cold",
    examples: ["Cold water", "A cold night"],
    image_url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=400",
    progress: 0,
  },
  {
    title: "Happy",
    word_origin: "Adjetivo feliz",
    word_target: "I'm very happy",
    examples: ["A happy smile", "Be happy"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    title: "Sad",
    word_origin: "Adjetivo triste",
    word_target: "Don't be sad",
    examples: ["A sad story", "Sad news"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Fast",
    word_origin: "Adjetivo rápido",
    word_target: "This car is fast",
    examples: ["Fast running", "Too fast"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Slow",
    word_origin: "Adjetivo lento",
    word_target: "Walk slowly",
    examples: ["A slow Internet", "Slow day"],
    image_url: "https://images.unsplash.com/photo-1491896293779-27c5b9bc26f3?w=400",
    progress: 0,
  },
  {
    title: "New",
    word_origin: "Adjetivo nuevo",
    word_target: "I have a new laptop",
    examples: ["New year", "New friends"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Old",
    word_origin: "Adjetivo viejo",
    word_target: "An old building",
    examples: ["Old friend", "How old are you?"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "Beautiful",
    word_origin: "Adjetivo hermoso",
    word_target: "A beautiful sunset",
    examples: ["Beautiful day", "So beautiful"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "Ugly",
    word_origin: "Adjetivo feo",
    word_target: "That's ugly",
    examples: ["Ugly weather", "Not ugly"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Short",
    word_origin: "Adjetivo corto",
    word_target: "That's a short walk",
    examples: ["Short hair", "Too short"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    title: "Long",
    word_origin: "Adjetivo largo",
    word_target: "A long journey",
    examples: ["Long hair", "Too long"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "Strong",
    word_origin: "Adjetivo fuerte",
    word_target: "You are strong",
    examples: ["Strong coffee", "Strong wind"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Weak",
    word_origin: "Adjetivo débil",
    word_target: "The signal is weak",
    examples: ["Weak tea", "Weak excuse"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Easy",
    word_origin: "Adjetivo fácil",
    word_target: "This is easy",
    examples: ["Easy problem", "Too easy"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Difficult",
    word_origin: "Adjetivo difícil",
    word_target: "That's difficult",
    examples: ["Difficult question", "Very difficult"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Cheap",
    word_origin: "Adjetivo barato",
    word_target: "It's very cheap",
    examples: ["Cheap food", "Too cheap"],
    image_url: "https://images.unsplash.com/photo-1553729754-5f935e49c61a?w=400",
    progress: 0,
  },
  {
    title: "Expensive",
    word_origin: "Adjetivo caro",
    word_target: "That's expensive",
    examples: ["Expensive car", "Too expensive"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Clean",
    word_origin: "Adjetivo limpio",
    word_target: "Keep it clean",
    examples: ["Clean room", "Very clean"],
    image_url: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400",
    progress: 0,
  },
  {
    title: "Dirty",
    word_origin: "Adjetivo sucio",
    word_target: "The floor is dirty",
    examples: ["Dirty clothes", "Very dirty"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Wet",
    word_origin: "Adjetivo mojado",
    word_target: "My clothes are wet",
    examples: ["Wet floor", "Soaking wet"],
    image_url: "https://images.unsplash.com/photo-1509803874385-db7c23645e71?w=400",
    progress: 0,
  },
  {
    title: "Dry",
    word_origin: "Adjetivo seco",
    word_target: "The weather is dry",
    examples: ["Dry skin", "Very dry"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "Here",
    word_origin: "Adverbio lugar",
    word_target: "Come here, please",
    examples: ["Here you go", "Over here"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "There",
    word_origin: "Adverbio lugar",
    word_target: "I see it there",
    examples: ["Over there", "There you are"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "Now",
    word_origin: "Adverbio tiempo",
    word_target: "Do it now",
    examples: ["Right now", "Now and then"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    title: "Then",
    word_origin: "Adverbio tiempo",
    word_target: "And then what?",
    examples: ["Back then", "Now and then"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "Today",
    word_origin: "Adverbio tiempo",
    word_target: "See you today",
    examples: ["Today is Monday", "Not today"],
    image_url: "https://images.unsplash.com/photo-1495567720989-cebfdc6d5fb3?w=400",
    progress: 0,
  },
  {
    title: "Tomorrow",
    word_origin: "Adverbio tiempo",
    word_target: "See you tomorrow",
    examples: ["Tomorrow morning", "See you tomorrow"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "Yesterday",
    word_origin: "Adverbio tiempo",
    word_target: "I saw it yesterday",
    examples: ["Yesterday evening", "Not yesterday"],
    image_url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=400",
    progress: 0,
  },
  {
    title: "Always",
    word_origin: "Adverbio frecuencia",
    word_target: "I always help",
    examples: ["Always happy", "Always here"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Never",
    word_origin: "Adverbio frecuencia",
    word_target: "Never give up",
    examples: ["Never again", "Never mind"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Very",
    word_origin: "Adverbio intensidad",
    word_target: "It's very good",
    examples: ["Very fast", "Very happy"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Only",
    word_origin: "Adverbio",
    word_target: "Only you can decide",
    examples: ["Only one left", "Only today"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "And",
    word_origin: "Conjunción",
    word_target: "Coffee and tea",
    examples: ["You and me", "Here and there"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    title: "Or",
    word_origin: "Conjunción",
    word_target: "Coffee or tea?",
    examples: ["Now or never", "This or that"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "But",
    word_origin: "Conjunción",
    word_target: "I like it but not today",
    examples: ["But why?", "Try but fail"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "In",
    word_origin: "Preposición",
    word_target: "In the house",
    examples: ["In time", "In Mexico"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    title: "On",
    word_origin: "Preposición",
    word_target: "On the table",
    examples: ["On Monday", "On top"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    title: "At",
    word_origin: "Preposición",
    word_target: "At home",
    examples: ["At work", "At night"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    title: "From",
    word_origin: "Preposición",
    word_target: "From Mexico",
    examples: ["From here", "From now on"],
    image_url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    progress: 0,
  },
  {
    title: "To",
    word_origin: "Preposición",
    word_target: "Go to school",
    examples: ["To you", "To the store"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    title: "Of",
    word_origin: "Preposición",
    word_target: "A cup of tea",
    examples: ["Of course", "All of it"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    title: "With",
    word_origin: "Preposición",
    word_target: "Go with me",
    examples: ["With love", "With care"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "By",
    word_origin: "Preposición",
    word_target: "By the way",
    examples: ["By car", "By hand"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "For",
    word_origin: "Preposición",
    word_target: "This is for you",
    examples: ["For example", "For now"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    title: "About",
    word_origin: "Preposición",
    word_target: "Tell me about it",
    examples: ["About time", "What about you?"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "One",
    word_origin: "Número",
    word_target: "I have one book",
    examples: ["One day", "Number one"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    title: "Two",
    word_origin: "Número",
    word_target: "I have two hands",
    examples: ["Two days", "Two people"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Three",
    word_origin: "Número",
    word_target: "I have three books",
    examples: ["Three times", "Three days"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Help",
    word_origin: "Verbo ayudar",
    word_target: "Can you help me?",
    examples: ["Help me please", "I can help"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    title: "Open",
    word_origin: "Verbo abrir",
    word_target: "Open the door",
    examples: ["Open your eyes", "The store is open"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    title: "Close",
    word_origin: "Verbo cerrar",
    word_target: "Close the door",
    examples: ["Close your eyes", "Close enough"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    title: "Run",
    word_origin: "Verbo correr",
    word_target: "Let's run",
    examples: ["Run fast", "Run away"],
    image_url: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400",
    progress: 0,
  },
  {
    title: "Walk",
    word_origin: "Verbo caminar",
    word_target: "Let's walk",
    examples: ["Walk slowly", "Walk home"],
    image_url: "https://images.unsplash.com/photo-1491195262715-f3e0614bcf51?w=400",
    progress: 0,
  },
];