export const basicWords = [
  {
    word: "Hello",
    word_origin: "Saludo común",
    word_target: "Hello, how are you?",
    word_translation: "Hola",
    examples: ["Hello, my name is Jorge", "Hello everyone!"],
    examples_es: ["Hola, mi nombre es Jorge", "¡Hola a todos!"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Goodbye",
    word_origin: "Despedida",
    word_target: "Goodbye, see you soon",
    word_translation: "Adiós",
    examples: ["Goodbye my friend", "Goodbye for now"],
    examples_es: ["Adiós, amigo mío", "Adiós por ahora"],
    similar_words: ["ventana", "familia", "trabajo", "persona", "palacio", "caminos", "palabra", "planeta", "canción", "corazón"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Thank you",
    word_origin: "Expresión de gratitud",
    word_target: "Thank you for your help",
    word_translation: "Gracias",
    examples: ["Thank you very much", "Thank you so much"],
    examples_es: ["Muchas gracias", "Muchísimas gracias"],
    similar_words: ["chocolate", "mariposas", "primavera", "compañero", "aventuras", "caballero", "panadería", "universos", "enamorado", "solitario"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Please",
    word_origin: "Palabra de cortesía",
    word_target: "Please pass the salt",
    word_translation: "Por favor",
    examples: ["Please help me", "Please come here"],
    examples_es: ["Por favor, ayúdame", "Por favor, ven aquí"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "número", "objeto"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Yes",
    word_origin: "Afirmación",
    word_target: "Yes, I agree",
    word_translation: "Sí",
    examples: ["Yes, that's correct", "Yes, I understand"],
    examples_es: ["Sí, eso es correcto", "Sí, entiendo"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "No",
    word_origin: "Negación",
    word_target: "No, I don't think so",
    word_translation: "No",
    examples: ["No, thank you", "No, I can't"],
    examples_es: ["No, gracias", "No, no puedo"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Sorry",
    word_origin: "Disculpa",
    word_target: "Sorry, I made a mistake",
    word_translation: "Lo siento",
    examples: ["Sorry about that", "I'm sorry for being late"],
    examples_es: ["Lo siento por eso", "Lo siento por llegar tarde"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Excuse me",
    word_origin: "Llamar la atención",
    word_target: "Excuse me, where is the bathroom?",
    word_translation: "Disculpe",
    examples: ["Excuse me, can you help me?", "Excuse me, sir"],
    examples_es: ["Disculpe, ¿puede ayudarme?", "Disculpe, señor"],
    similar_words: ["chocolate", "mariposas", "primavera", "compañero", "aventuras", "caballero", "panadería", "universos", "enamorado", "solitario"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "What",
    word_origin: "Pregunta sobre cosa",
    word_target: "What is your name?",
    word_translation: "Qué",
    examples: ["What time is it?", "What do you want?"],
    examples_es: ["¿Qué hora es?", "¿Qué quieres?"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "When",
    word_origin: "Pregunta sobre tiempo",
    word_target: "When are you coming?",
    word_translation: "Cuándo",
    examples: ["When is the meeting?", "When did you arrive?"],
    examples_es: ["¿Cuándo es la reunión?", "¿Cuándo llegaste?"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Where",
    word_origin: "Pregunta sobre lugar",
    word_target: "Where is the station?",
    word_translation: "Dónde",
    examples: ["Where do you live?", "Where are you going?"],
    examples_es: ["¿Dónde vives?", "¿A dónde vas?"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Who",
    word_origin: "Pregunta sobre persona",
    word_target: "Who is your friend?",
    word_translation: "Quién",
    examples: ["Who called you?", "Who are they?"],
    examples_es: ["¿Quién te llamó?", "¿Quiénes son ellos?"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Why",
    word_origin: "Pregunta sobre razón",
    word_target: "Why are you here?",
    word_translation: "Por qué",
    examples: ["Why did you leave?", "Why is it important?"],
    examples_es: ["¿Por qué te fuiste?", "¿Por qué es importante?"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "How",
    word_origin: "Pregunta sobre manera",
    word_target: "How are you today?",
    word_translation: "Cómo",
    examples: ["How do you do it?", "How much is it?"],
    examples_es: ["¿Cómo lo haces?", "¿Cuánto cuesta?"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "I",
    word_origin: "Pronombre personal",
    word_target: "I am a developer",
    word_translation: "Yo",
    examples: ["I like programming", "I am from Mexico"],
    examples_es: ["Me gusta programar", "Soy de México"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "You",
    word_origin: "Pronombre personal",
    word_target: "You are welcome",
    word_translation: "Tú",
    examples: ["You are smart", "You can do it"],
    examples_es: ["Eres inteligente", "Tú puedes hacerlo"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "He",
    word_origin: "Pronombre personal masculino",
    word_target: "He is a mechanic",
    word_translation: "Él",
    examples: ["He works hard", "He is from Torreón"],
    examples_es: ["Él trabaja duro", "Él es de Torreón"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    progress: 0,
  },
  {
    word: "She",
    word_origin: "Pronombre personal femenino",
    word_target: "She is a teacher",
    word_translation: "Ella",
    examples: ["She likes reading", "She is very kind"],
    examples_es: ["A ella le gusta leer", "Ella es muy amable"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    progress: 0,
  },
  {
    word: "It",
    word_origin: "Pronombre para cosas",
    word_target: "It is a car",
    word_translation: "Ello",
    examples: ["It's beautiful", "It works well"],
    examples_es: ["Es hermoso", "Funciona bien"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=400",
    progress: 0,
  },
  {
    word: "We",
    word_origin: "Pronombre plural inclusivo",
    word_target: "We are developers",
    word_translation: "Nosotros",
    examples: ["We work together", "We are friends"],
    examples_es: ["Trabajamos juntos", "Somos amigos"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "They",
    word_origin: "Pronombre plural",
    word_target: "They are students",
    word_translation: "Ellos",
    examples: ["They are happy", "They live here"],
    examples_es: ["Ellos están felices", "Ellos viven aquí"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "My",
    word_origin: "Pronombre posesivo",
    word_target: "This is my house",
    word_translation: "Mi",
    examples: ["My name is Jorge", "My car is red"],
    examples_es: ["Mi nombre es Jorge", "Mi coche es rojo"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    word: "Your",
    word_origin: "Pronombre posesivo",
    word_target: "What is your name?",
    word_translation: "Tu",
    examples: ["Your book is here", "Your phone is ringing"],
    examples_es: ["Tu libro está aquí", "Tu teléfono está sonando"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "His",
    word_origin: "Pronombre posesivo masculino",
    word_target: "This is his bicycle",
    word_translation: "Su",
    examples: ["His house is big", "His job is interesting"],
    examples_es: ["Su casa es grande", "Su trabajo es interesante"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    progress: 0,
  },
  {
    word: "Her",
    word_origin: "Pronombre posesivo femenino",
    word_target: "This is her desk",
    word_translation: "Su",
    examples: ["Her dress is beautiful", "Her name is Maria"],
    examples_es: ["Su vestido es hermoso", "Su nombre es María"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Is",
    word_origin: "Verbo ser/estar",
    word_target: "This is important",
    word_translation: "Es",
    examples: ["She is a doctor", "It is sunny today"],
    examples_es: ["Ella es doctora", "Hoy está soleado"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Are",
    word_origin: "Verbo ser/estar",
    word_target: "You are amazing",
    word_translation: "Son",
    examples: ["We are friends", "They are here"],
    examples_es: ["Somos amigos", "Ellos están aquí"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Am",
    word_origin: "Verbo ser/estar",
    word_target: "I am happy",
    word_translation: "Soy",
    examples: ["I am a developer", "I am learning English"],
    examples_es: ["Soy desarrollador", "Estoy aprendiendo inglés"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Have",
    word_origin: "Verbo tener",
    word_target: "I have a car",
    word_translation: "Tener",
    examples: ["You have time", "They have books"],
    examples_es: ["Tienes tiempo", "Ellos tienen libros"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Has",
    word_origin: "Verbo tener (tercera persona)",
    word_target: "He has a laptop",
    word_translation: "Tiene",
    examples: ["She has money", "It has wheels"],
    examples_es: ["Ella tiene dinero", "Tiene ruedas"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Do",
    word_origin: "Verbo hacer",
    word_target: "What do you do?",
    word_translation: "Hacer",
    examples: ["I do my homework", "You do great work"],
    examples_es: ["Hago mi tarea", "Haces un gran trabajo"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Does",
    word_origin: "Verbo hacer (tercera persona)",
    word_target: "Does he like it?",
    word_translation: "Hace",
    examples: ["She does her best", "It does work"],
    examples_es: ["Ella da lo mejor de sí", "Sí funciona"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Go",
    word_origin: "Verbo ir",
    word_target: "Let's go to the beach",
    word_translation: "Ir",
    examples: ["I go to work", "We go together"],
    examples_es: ["Voy al trabajo", "Vamos juntos"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "Come",
    word_origin: "Verbo venir",
    word_target: "Come here, please",
    word_translation: "Venir",
    examples: ["She comes tomorrow", "They come early"],
    examples_es: ["Ella viene mañana", "Ellos llegan temprano"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Like",
    word_origin: "Verbo gustar",
    word_target: "I like programming",
    word_translation: "Gustar",
    examples: ["You like coffee", "They like sports"],
    examples_es: ["Te gusta el café", "A ellos les gustan los deportes"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Love",
    word_origin: "Verbo amar",
    word_target: "I love my family",
    word_translation: "Amor",
    examples: ["She loves her job", "We love this place"],
    examples_es: ["A ella le encanta su trabajo", "Amamos este lugar"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    word: "Want",
    word_origin: "Verbo querer",
    word_target: "I want to learn English",
    word_translation: "Querer",
    examples: ["Do you want coffee?", "They want to help"],
    examples_es: ["¿Quieres café?", "Ellos quieren ayudar"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Need",
    word_origin: "Verbo necesitar",
    word_target: "I need your help",
    word_translation: "Necesitar",
    examples: ["She needs a break", "We need time"],
    examples_es: ["Ella necesita un descanso", "Necesitamos tiempo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Can",
    word_origin: "Verbo modal (poder)",
    word_target: "I can help you",
    word_translation: "Poder",
    examples: ["You can do it", "He can speak Spanish"],
    examples_es: ["Tú puedes hacerlo", "Él puede hablar español"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Make",
    word_origin: "Verbo hacer/crear",
    word_target: "Let's make a plan",
    word_translation: "Crear",
    examples: ["I make websites", "She makes coffee"],
    examples_es: ["Hago sitios web", "Ella hace café"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Take",
    word_origin: "Verbo tomar",
    word_target: "Take this book",
    word_translation: "Tomar",
    examples: ["I take a break", "You take the first turn"],
    examples_es: ["Me tomo un descanso", "Tú tomas el primer turno"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Give",
    word_origin: "Verbo dar",
    word_target: "Give me the keys",
    word_translation: "Dar",
    examples: ["I give you my word", "She gives advice"],
    examples_es: ["Te doy mi palabra", "Ella da consejos"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Work",
    word_origin: "Verbo trabajar",
    word_target: "I work as a mechanic",
    word_translation: "Trabajar",
    examples: ["You work hard", "We work together"],
    examples_es: ["Trabajas duro", "Trabajamos juntos"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Learn",
    word_origin: "Verbo aprender",
    word_target: "I learn every day",
    word_translation: "Aprender",
    examples: ["You learn fast", "They learn English"],
    examples_es: ["Aprendes rápido", "Ellos aprenden inglés"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Think",
    word_origin: "Verbo pensar",
    word_target: "I think it's good",
    word_translation: "Pensar",
    examples: ["You think too much", "She thinks it's funny"],
    examples_es: ["Piensas demasiado", "Ella piensa que es gracioso"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Know",
    word_origin: "Verbo saber/conocer",
    word_target: "I know the answer",
    word_translation: "Saber",
    examples: ["You know me well", "Do they know about it?"],
    examples_es: ["Tú me conoces bien", "¿Ellos saben de eso?"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Say",
    word_origin: "Verbo decir",
    word_target: "What do you say?",
    word_translation: "Decir",
    examples: ["I say it's time", "She says hello"],
    examples_es: ["Digo que es hora", "Ella dice hola"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "See",
    word_origin: "Verbo ver",
    word_target: "I see the problem",
    word_translation: "Ver",
    examples: ["You see it too", "They see the light"],
    examples_es: ["Tú también lo ves", "Ellos ven la luz"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Get",
    word_origin: "Verbo obtener",
    word_target: "I get it now",
    word_translation: "Obtener",
    examples: ["You get the idea", "She gets tired easily"],
    examples_es: ["Tú entiendes la idea", "Ella se cansa fácilmente"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Man",
    word_origin: "Sustantivo hombre",
    word_target: "That man is tall",
    word_translation: "Hombre",
    examples: ["A man walked in", "The man works here"],
    examples_es: ["Un hombre entró", "El hombre trabaja aquí"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    progress: 0,
  },
  {
    word: "Woman",
    word_origin: "Sustantivo mujer",
    word_target: "The woman is smart",
    word_translation: "Mujer",
    examples: ["A woman called you", "The woman teaches well"],
    examples_es: ["Una mujer te llamó", "La mujer enseña bien"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    progress: 0,
  },
  {
    word: "Child",
    word_origin: "Sustantivo niño",
    word_target: "The child is happy",
    word_translation: "Niño",
    examples: ["A child is playing", "The children laugh"],
    examples_es: ["Un niño está jugando", "Los niños ríen"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1503454537688-e47a5cb0adf0?w=400",
    progress: 0,
  },
  {
    word: "Day",
    word_origin: "Sustantivo día",
    word_target: "Today is a good day",
    word_translation: "Día",
    examples: ["Every day is new", "The day is sunny"],
    examples_es: ["Cada día es nuevo", "El día está soleado"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1495567720989-cebfdc6d5fb3?w=400",
    progress: 0,
  },
  {
    word: "Night",
    word_origin: "Sustantivo noche",
    word_target: "Good night, friend",
    word_translation: "Noche",
    examples: ["The night is quiet", "All night long"],
    examples_es: ["La noche está tranquila", "Toda la noche"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "llano", "perro", "orden"],
    image_url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=400",
    progress: 0,
  },
  {
    word: "Time",
    word_origin: "Sustantivo tiempo",
    word_target: "What time is it?",
    word_translation: "Tiempo",
    examples: ["It's time to go", "We have time"],
    examples_es: ["Es hora de irse", "Tenemos tiempo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    word: "House",
    word_origin: "Sustantivo casa",
    word_target: "This is my house",
    word_translation: "Casa",
    examples: ["A big house", "Go to the house"],
    examples_es: ["Una casa grande", "Ve a la casa"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    word: "Car",
    word_origin: "Sustantivo coche",
    word_target: "I have a car",
    word_translation: "Coche",
    examples: ["A red car", "The car is fast"],
    examples_es: ["Un coche rojo", "El coche es rápido"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Book",
    word_origin: "Sustantivo libro",
    word_target: "I like this book",
    word_translation: "Libro",
    examples: ["A good book", "Read the book"],
    examples_es: ["Un buen libro", "Lee el libro"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400",
    progress: 0,
  },
  {
    word: "Water",
    word_origin: "Sustantivo agua",
    word_target: "Drink some water",
    word_translation: "Agua",
    examples: ["Clear water", "The water is cold"],
    examples_es: ["Agua clara", "El agua está fría"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1509803874385-db7c23645e71?w=400",
    progress: 0,
  },
  {
    word: "Food",
    word_origin: "Sustantivo comida",
    word_target: "The food is delicious",
    word_translation: "Comida",
    examples: ["Good food", "Eat your food"],
    examples_es: ["Buena comida", "Come tu comida"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1495577913117-a0241e4ec97d?w=400",
    progress: 0,
  },
  {
    word: "Money",
    word_origin: "Sustantivo dinero",
    word_target: "I need money",
    word_translation: "Dinero",
    examples: ["Save money", "Spend money wisely"],
    examples_es: ["Ahorra dinero", "Gasta el dinero sabiamente"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1553729754-5f935e49c61a?w=400",
    progress: 0,
  },
  {
    word: "Computer",
    word_origin: "Sustantivo computadora",
    word_target: "I use a computer",
    word_translation: "Computadora",
    examples: ["A fast computer", "The computer works"],
    examples_es: ["Una computadora rápida", "La computadora funciona"],
    similar_words: ["aventura", "montañas", "programa", "elefante", "cocinero", "palabras", "ventanas", "personas", "pulseras", "hermanos"],
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    progress: 0,
  },
  {
    word: "Phone",
    word_origin: "Sustantivo teléfono",
    word_target: "My phone is ringing",
    word_translation: "Teléfono",
    examples: ["A new phone", "Check your phone"],
    examples_es: ["Un teléfono nuevo", "Revisa tu teléfono"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=400",
    progress: 0,
  },
  {
    word: "Friend",
    word_origin: "Sustantivo amigo",
    word_target: "You are my friend",
    word_translation: "Amigo",
    examples: ["A good friend", "Make new friends"],
    examples_es: ["Un buen amigo", "Haz nuevos amigos"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "número", "objeto"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Family",
    word_origin: "Sustantivo familia",
    word_target: "My family is happy",
    word_translation: "Familia",
    examples: ["A big family", "Family is important"],
    examples_es: ["Una familia grande", "La familia es importante"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "número", "objeto"],
    image_url: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400",
    progress: 0,
  },
  {
    word: "Work",
    word_origin: "Sustantivo trabajo",
    word_target: "I love my work",
    word_translation: "Trabajo",
    examples: ["Hard work", "Go to work"],
    examples_es: ["Trabajo duro", "Ve al trabajo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "School",
    word_origin: "Sustantivo escuela",
    word_target: "Go to school",
    word_translation: "Escuela",
    examples: ["A good school", "The school is big"],
    examples_es: ["Una buena escuela", "La escuela es grande"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "número", "objeto"],
    image_url: "https://images.unsplash.com/photo-1427504494785-cdfe4e2e4e28?w=400",
    progress: 0,
  },
  {
    word: "City",
    word_origin: "Sustantivo ciudad",
    word_target: "I live in a city",
    word_translation: "Ciudad",
    examples: ["A big city", "The city is busy"],
    examples_es: ["Una ciudad grande", "La ciudad está ocupada"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400",
    progress: 0,
  },
  {
    word: "Country",
    word_origin: "Sustantivo país",
    word_target: "Mexico is my country",
    word_translation: "País",
    examples: ["A beautiful country", "Visit the country"],
    examples_es: ["Un país hermoso", "Visita el país"],
    similar_words: ["ventana", "familia", "trabajo", "persona", "palacio", "caminos", "palabra", "planeta", "canción", "corazón"],
    image_url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    progress: 0,
  },
  {
    word: "Hand",
    word_origin: "Sustantivo mano",
    word_target: "Raise your hand",
    word_translation: "Mano",
    examples: ["Right hand", "Hold my hand"],
    examples_es: ["Mano derecha", "Toma mi mano"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "boca", "taza"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    word: "Head",
    word_origin: "Sustantivo cabeza",
    word_target: "My head hurts",
    word_translation: "Cabeza",
    examples: ["Shake your head", "The head office"],
    examples_es: ["Sacude tu cabeza", "La oficina central"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    progress: 0,
  },
  {
    word: "Eye",
    word_origin: "Sustantivo ojo",
    word_target: "Look in my eye",
    word_translation: "Ojo",
    examples: ["Blue eyes", "Close your eyes"],
    examples_es: ["Ojos azules", "Cierra los ojos"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "sal", "uno", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    word: "Heart",
    word_origin: "Sustantivo corazón",
    word_target: "Follow your heart",
    word_translation: "Corazón",
    examples: ["A kind heart", "From the heart"],
    examples_es: ["Un corazón bondadoso", "De corazón"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    word: "Color",
    word_origin: "Sustantivo color",
    word_target: "What's your favorite color?",
    word_translation: "Color",
    examples: ["A bright color", "Choose a color"],
    examples_es: ["Un color brillante", "Elige un color"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1551888016-10a93f3a77b0?w=400",
    progress: 0,
  },
  {
    word: "Number",
    word_origin: "Sustantivo número",
    word_target: "Call this number",
    word_translation: "Número",
    examples: ["A big number", "What number is it?"],
    examples_es: ["Un número grande", "¿Qué número es?"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "objeto", "camino"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    word: "Good",
    word_origin: "Adjetivo bueno",
    word_target: "That's a good idea",
    word_translation: "Bueno",
    examples: ["Good morning", "Good job"],
    examples_es: ["Buenos días", "Buen trabajo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Bad",
    word_origin: "Adjetivo malo",
    word_target: "This is bad weather",
    word_translation: "Malo",
    examples: ["A bad day", "Bad luck"],
    examples_es: ["Un mal día", "Mala suerte"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Big",
    word_origin: "Adjetivo grande",
    word_target: "A big house",
    word_translation: "Grande",
    examples: ["A big tree", "Too big"],
    examples_es: ["Un árbol grande", "Demasiado grande"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "Small",
    word_origin: "Adjetivo pequeño",
    word_target: "A small dog",
    word_translation: "Pequeño",
    examples: ["Small size", "Very small"],
    examples_es: ["Talla pequeña", "Muy pequeño"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Hot",
    word_origin: "Adjetivo caliente",
    word_target: "The coffee is hot",
    word_translation: "Caliente",
    examples: ["A hot day", "Hot water"],
    examples_es: ["Un día caluroso", "Agua caliente"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "Cold",
    word_origin: "Adjetivo frío",
    word_target: "It's very cold",
    word_translation: "Frío",
    examples: ["Cold water", "A cold night"],
    examples_es: ["Agua fría", "Una noche fría"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=400",
    progress: 0,
  },
  {
    word: "Happy",
    word_origin: "Adjetivo feliz",
    word_target: "I'm very happy",
    word_translation: "Feliz",
    examples: ["A happy smile", "Be happy"],
    examples_es: ["Una sonrisa feliz", "Sé feliz"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    word: "Sad",
    word_origin: "Adjetivo triste",
    word_target: "Don't be sad",
    word_translation: "Triste",
    examples: ["A sad story", "Sad news"],
    examples_es: ["Una historia triste", "Malas noticias"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Fast",
    word_origin: "Adjetivo rápido",
    word_target: "This car is fast",
    word_translation: "Rápido",
    examples: ["Fast running", "Too fast"],
    examples_es: ["Correr rápido", "Demasiado rápido"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Slow",
    word_origin: "Adjetivo lento",
    word_target: "Walk slowly",
    word_translation: "Lento",
    examples: ["A slow Internet", "Slow day"],
    examples_es: ["Un internet lento", "Día tranquilo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1491896293779-27c5b9bc26f3?w=400",
    progress: 0,
  },
  {
    word: "New",
    word_origin: "Adjetivo nuevo",
    word_target: "I have a new laptop",
    word_translation: "Nuevo",
    examples: ["New year", "New friends"],
    examples_es: ["Año nuevo", "Nuevos amigos"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Old",
    word_origin: "Adjetivo viejo",
    word_target: "An old building",
    word_translation: "Viejo",
    examples: ["Old friend", "How old are you?"],
    examples_es: ["Viejo amigo", "¿Cuántos años tienes?"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "Beautiful",
    word_origin: "Adjetivo hermoso",
    word_target: "A beautiful sunset",
    word_translation: "Hermoso",
    examples: ["Beautiful day", "So beautiful"],
    examples_es: ["Día hermoso", "Tan hermoso"],
    similar_words: ["chocolate", "mariposas", "primavera", "compañero", "aventuras", "caballero", "panadería", "universos", "enamorado", "solitario"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "Ugly",
    word_origin: "Adjetivo feo",
    word_target: "That's ugly",
    word_translation: "Feo",
    examples: ["Ugly weather", "Not ugly"],
    examples_es: ["Mal tiempo", "No es feo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Short",
    word_origin: "Adjetivo corto",
    word_target: "That's a short walk",
    word_translation: "Corto",
    examples: ["Short hair", "Too short"],
    examples_es: ["Cabello corto", "Demasiado corto"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    word: "Long",
    word_origin: "Adjetivo largo",
    word_target: "A long journey",
    word_translation: "Largo",
    examples: ["Long hair", "Too long"],
    examples_es: ["Cabello largo", "Demasiado largo"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "Strong",
    word_origin: "Adjetivo fuerte",
    word_target: "You are strong",
    word_translation: "Fuerte",
    examples: ["Strong coffee", "Strong wind"],
    examples_es: ["Café fuerte", "Viento fuerte"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "número", "objeto"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Weak",
    word_origin: "Adjetivo débil",
    word_target: "The signal is weak",
    word_translation: "Débil",
    examples: ["Weak tea", "Weak excuse"],
    examples_es: ["Té suave", "Excusa débil"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Easy",
    word_origin: "Adjetivo fácil",
    word_target: "This is easy",
    word_translation: "Fácil",
    examples: ["Easy problem", "Too easy"],
    examples_es: ["Problema fácil", "Demasiado fácil"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Difficult",
    word_origin: "Adjetivo difícil",
    word_target: "That's difficult",
    word_translation: "Difícil",
    examples: ["Difficult question", "Very difficult"],
    examples_es: ["Pregunta difícil", "Muy difícil"],
    similar_words: ["chocolate", "mariposas", "primavera", "compañero", "aventuras", "caballero", "panadería", "universos", "enamorado", "solitario"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Cheap",
    word_origin: "Adjetivo barato",
    word_target: "It's very cheap",
    word_translation: "Barato",
    examples: ["Cheap food", "Too cheap"],
    examples_es: ["Comida barata", "Demasiado barato"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1553729754-5f935e49c61a?w=400",
    progress: 0,
  },
  {
    word: "Expensive",
    word_origin: "Adjetivo caro",
    word_target: "That's expensive",
    word_translation: "Caro",
    examples: ["Expensive car", "Too expensive"],
    examples_es: ["Coche caro", "Demasiado caro"],
    similar_words: ["chocolate", "mariposas", "primavera", "compañero", "aventuras", "caballero", "panadería", "universos", "enamorado", "solitario"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Clean",
    word_origin: "Adjetivo limpio",
    word_target: "Keep it clean",
    word_translation: "Limpio",
    examples: ["Clean room", "Very clean"],
    examples_es: ["Cuarto limpio", "Muy limpio"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400",
    progress: 0,
  },
  {
    word: "Dirty",
    word_origin: "Adjetivo sucio",
    word_target: "The floor is dirty",
    word_translation: "Sucio",
    examples: ["Dirty clothes", "Very dirty"],
    examples_es: ["Ropa sucia", "Muy sucio"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Wet",
    word_origin: "Adjetivo mojado",
    word_target: "My clothes are wet",
    word_translation: "Mojado",
    examples: ["Wet floor", "Soaking wet"],
    examples_es: ["Piso mojado", "Completamente mojado"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1509803874385-db7c23645e71?w=400",
    progress: 0,
  },
  {
    word: "Dry",
    word_origin: "Adjetivo seco",
    word_target: "The weather is dry",
    word_translation: "Seco",
    examples: ["Dry skin", "Very dry"],
    examples_es: ["Piel seca", "Muy seco"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "Here",
    word_origin: "Adverbio lugar",
    word_target: "Come here, please",
    word_translation: "Aquí",
    examples: ["Here you go", "Over here"],
    examples_es: ["Aquí tienes", "Por aquí"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "There",
    word_origin: "Adverbio lugar",
    word_target: "I see it there",
    word_translation: "Allí",
    examples: ["Over there", "There you are"],
    examples_es: ["Por allá", "Ahí estás"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "Now",
    word_origin: "Adverbio tiempo",
    word_target: "Do it now",
    word_translation: "Ahora",
    examples: ["Right now", "Now and then"],
    examples_es: ["Ahora mismo", "De vez en cuando"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    word: "Then",
    word_origin: "Adverbio tiempo",
    word_target: "And then what?",
    word_translation: "Entonces",
    examples: ["Back then", "Now and then"],
    examples_es: ["En aquel entonces", "De vez en cuando"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "Today",
    word_origin: "Adverbio tiempo",
    word_target: "See you today",
    word_translation: "Hoy",
    examples: ["Today is Monday", "Not today"],
    examples_es: ["Hoy es lunes", "Hoy no"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1495567720989-cebfdc6d5fb3?w=400",
    progress: 0,
  },
  {
    word: "Tomorrow",
    word_origin: "Adverbio tiempo",
    word_target: "See you tomorrow",
    word_translation: "Mañana",
    examples: ["Tomorrow morning", "See you tomorrow"],
    examples_es: ["Mañana por la mañana", "Hasta mañana"],
    similar_words: ["aventura", "montañas", "programa", "elefante", "cocinero", "palabras", "ventanas", "personas", "pulseras", "hermanos"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "Yesterday",
    word_origin: "Adverbio tiempo",
    word_target: "I saw it yesterday",
    word_translation: "Ayer",
    examples: ["Yesterday evening", "Not yesterday"],
    examples_es: ["Ayer por la tarde", "No ayer"],
    similar_words: ["chocolate", "mariposas", "primavera", "compañero", "aventuras", "caballero", "panadería", "universos", "enamorado", "solitario"],
    image_url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=400",
    progress: 0,
  },
  {
    word: "Always",
    word_origin: "Adverbio frecuencia",
    word_target: "I always help",
    word_translation: "Siempre",
    examples: ["Always happy", "Always here"],
    examples_es: ["Siempre feliz", "Siempre aquí"],
    similar_words: ["amigos", "ciudad", "blanco", "fresco", "grande", "helado", "jardín", "mantel", "número", "objeto"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Never",
    word_origin: "Adverbio frecuencia",
    word_target: "Never give up",
    word_translation: "Nunca",
    examples: ["Never again", "Never mind"],
    examples_es: ["Nunca más", "No importa"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Very",
    word_origin: "Adverbio intensidad",
    word_target: "It's very good",
    word_translation: "Muy",
    examples: ["Very fast", "Very happy"],
    examples_es: ["Muy rápido", "Muy feliz"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Only",
    word_origin: "Adverbio",
    word_target: "Only you can decide",
    word_translation: "Solo",
    examples: ["Only one left", "Only today"],
    examples_es: ["Solo queda uno", "Solo hoy"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "And",
    word_origin: "Conjunción",
    word_target: "Coffee and tea",
    word_translation: "Y",
    examples: ["You and me", "Here and there"],
    examples_es: ["Tú y yo", "Aquí y allá"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400",
    progress: 0,
  },
  {
    word: "Or",
    word_origin: "Conjunción",
    word_target: "Coffee or tea?",
    word_translation: "O",
    examples: ["Now or never", "This or that"],
    examples_es: ["Ahora o nunca", "Esto o aquello"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "But",
    word_origin: "Conjunción",
    word_target: "I like it but not today",
    word_translation: "Pero",
    examples: ["But why?", "Try but fail"],
    examples_es: ["¿Pero por qué?", "Intentar pero fallar"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "In",
    word_origin: "Preposición",
    word_target: "In the house",
    word_translation: "En",
    examples: ["In time", "In Mexico"],
    examples_es: ["A tiempo", "En México"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    word: "On",
    word_origin: "Preposición",
    word_target: "On the table",
    word_translation: "Sobre",
    examples: ["On Monday", "On top"],
    examples_es: ["El lunes", "Encima"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=400",
    progress: 0,
  },
  {
    word: "At",
    word_origin: "Preposición",
    word_target: "At home",
    word_translation: "En",
    examples: ["At work", "At night"],
    examples_es: ["En el trabajo", "En la noche"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    word: "From",
    word_origin: "Preposición",
    word_target: "From Mexico",
    word_translation: "Desde",
    examples: ["From here", "From now on"],
    examples_es: ["Desde aquí", "De ahora en adelante"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400",
    progress: 0,
  },
  {
    word: "To",
    word_origin: "Preposición",
    word_target: "Go to school",
    word_translation: "A",
    examples: ["To you", "To the store"],
    examples_es: ["Para ti", "A la tienda"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1488749367386-86a0e6a1fc7e?w=400",
    progress: 0,
  },
  {
    word: "Of",
    word_origin: "Preposición",
    word_target: "A cup of tea",
    word_translation: "De",
    examples: ["Of course", "All of it"],
    examples_es: ["Por supuesto", "Todo eso"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400",
    progress: 0,
  },
  {
    word: "With",
    word_origin: "Preposición",
    word_target: "Go with me",
    word_translation: "Con",
    examples: ["With love", "With care"],
    examples_es: ["Con amor", "Con cuidado"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "By",
    word_origin: "Preposición",
    word_target: "By the way",
    word_translation: "Por",
    examples: ["By car", "By hand"],
    examples_es: ["En coche", "A mano"],
    similar_words: ["yo", "él", "tú", "me", "te", "se", "la", "lo", "un", "su"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "For",
    word_origin: "Preposición",
    word_target: "This is for you",
    word_translation: "Para",
    examples: ["For example", "For now"],
    examples_es: ["Por ejemplo", "Por ahora"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    word: "About",
    word_origin: "Preposición",
    word_target: "Tell me about it",
    word_translation: "Sobre",
    examples: ["About time", "What about you?"],
    examples_es: ["Ya era hora", "¿Y tú qué?"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "One",
    word_origin: "Número",
    word_target: "I have one book",
    word_translation: "Uno",
    examples: ["One day", "Number one"],
    examples_es: ["Un día", "El número uno"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1516595022570-f06e0b74e63f?w=400",
    progress: 0,
  },
  {
    word: "Two",
    word_origin: "Número",
    word_target: "I have two hands",
    word_translation: "Dos",
    examples: ["Two days", "Two people"],
    examples_es: ["Dos días", "Dos personas"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "uno", "rey"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Three",
    word_origin: "Número",
    word_target: "I have three books",
    word_translation: "Tres",
    examples: ["Three times", "Three days"],
    examples_es: ["Tres veces", "Tres días"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Help",
    word_origin: "Verbo ayudar",
    word_target: "Can you help me?",
    word_translation: "Ayuda",
    examples: ["Help me please", "I can help"],
    examples_es: ["Ayúdame por favor", "Yo puedo ayudar"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400",
    progress: 0,
  },
  {
    word: "Open",
    word_origin: "Verbo abrir",
    word_target: "Open the door",
    word_translation: "Abrir",
    examples: ["Open your eyes", "The store is open"],
    examples_es: ["Abre los ojos", "La tienda está abierta"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    word: "Close",
    word_origin: "Verbo cerrar",
    word_target: "Close the door",
    word_translation: "Cerrar",
    examples: ["Close your eyes", "Close enough"],
    examples_es: ["Cierra los ojos", "Suficientemente cerca"],
    similar_words: ["campo", "playa", "vuelo", "canto", "globo", "fresa", "techo", "noche", "llano", "perro"],
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003d96eae?w=400",
    progress: 0,
  },
  {
    word: "Run",
    word_origin: "Verbo correr",
    word_target: "Let's run",
    word_translation: "Correr",
    examples: ["Run fast", "Run away"],
    examples_es: ["Corre rápido", "Huye"],
    similar_words: ["sol", "mar", "pan", "luz", "río", "paz", "ojo", "sal", "dos", "rey"],
    image_url: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400",
    progress: 0,
  },
  {
    word: "Walk",
    word_origin: "Verbo caminar",
    word_target: "Let's walk",
    word_translation: "Caminar",
    examples: ["Walk slowly", "Walk home"],
    examples_es: ["Camina despacio", "Camina a casa"],
    similar_words: ["pato", "gato", "tren", "mesa", "sopa", "vaca", "ropa", "luna", "mano", "boca"],
    image_url: "https://images.unsplash.com/photo-1491195262715-f3e0614bcf51?w=400",
    progress: 0,
  },
];
